trigger:
  - none  # No automatic trigger

resources:
  pipelines:
    - pipeline: ci-social-media-aks-application  # This is the alias that references the source pipeline
      source: "ci-social-media-aks-application"  # This is the actual name of the pipeline
      trigger:
        branches:
          include:
            - main  # Trigger the pipeline when there is a successful run in the main branch

pool:
  vmImage: 'ubuntu-latest'  # Using Ubuntu as the agent for the pipeline

stages:
  -  stage: Deploy
     jobs:
       -  job: Deploy the application in aks
          steps:
            - task: DownloadBuildArtifacts@1
              inputs:
                buildType: 'current'
                downloadType: 'single'
                downloadPath: '$(System.ArtifactsDirectory)'
